"""Add booking delete logic

Revision ID: 3a1af4a4d60e
Revises: 336109ac4c55
Create Date: 2025-07-18 17:00:32.997818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1af4a4d60e'
down_revision = '336109ac4c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_hours', sa.Integer(), nullable=False))

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_spaces_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_spaces_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('number_of_hours')

    # ### end Alembic commands ###
